/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-03 07:59:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.board_002dform;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class trip_002dboard_002dform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>내 여행기 작성 폼</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/font/font.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/board-form/trip-board-form.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<app-root>\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/mypage/mypage-modal.jsp", out, false);
      out.write("\r\n");
      out.write("		<app-write-travel-note>\r\n");
      out.write("		<div id=\"content\">\r\n");
      out.write("			<div class=\"in_wrap\">\r\n");
      out.write("				<section class=\"editor_wrap\">\r\n");
      out.write("\r\n");
      out.write("					<input class=\"hidden\" id=\"default-image\">\r\n");
      out.write("					<div class=\"write_form pdt50\">\r\n");
      out.write("						<form class=\"final-form\">\r\n");
      out.write("							<div class=\"inner\">\r\n");
      out.write("								<input formcontrolname=\"travelogue_title\"\r\n");
      out.write("									placeholder=\"제목을 입력해 주세요\" type=\"text\" maxlength=\"30\"\r\n");
      out.write("									class=\"txtbox st1  ng-pristine ng-invalid\"> <span\r\n");
      out.write("									class=\"desc c_st02 cant-submit\" style=\"display: none;\">\r\n");
      out.write("									제목 입력은 필수입니다. </span>\r\n");
      out.write("								<!---->\r\n");
      out.write("								<!---->\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"inner date_form\">\r\n");
      out.write("								<div class=\"cal-container cal-none\">\r\n");
      out.write("									<div class=\"my-calendar clearfix\">\r\n");
      out.write("										<div class=\"clicked-date\" style=\"display: none;\">\r\n");
      out.write("											<div class=\"cal-day\"></div>\r\n");
      out.write("											<div class=\"cal-date\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"calendar-box\">\r\n");
      out.write("											<div class=\"ctr-box clearfix\">\r\n");
      out.write("												<button type=\"button\" title=\"prev\" class=\"btn-cal prev\">\r\n");
      out.write("												</button>\r\n");
      out.write("												<span class=\"cal-month\"></span> <span class=\"cal-year\"></span>\r\n");
      out.write("												<button type=\"button\" title=\"next\" class=\"btn-cal next\">\r\n");
      out.write("												</button>\r\n");
      out.write("											</div>\r\n");
      out.write("											<table class=\"cal-table\">\r\n");
      out.write("												<thead>\r\n");
      out.write("													<tr>\r\n");
      out.write("														<th>S</th>\r\n");
      out.write("														<th>M</th>\r\n");
      out.write("														<th>T</th>\r\n");
      out.write("														<th>W</th>\r\n");
      out.write("														<th>T</th>\r\n");
      out.write("														<th>F</th>\r\n");
      out.write("														<th>S</th>\r\n");
      out.write("													</tr>\r\n");
      out.write("												</thead>\r\n");
      out.write("												<tbody class=\"cal-body\"></tbody>\r\n");
      out.write("											</table>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!-- // .my-calendar -->\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<input type=\"text\" disabled placeholder=\"여행시작\"\r\n");
      out.write("									class=\"trip-start input-day\">\r\n");
      out.write("								<mat-datepicker-toggle class=\"calender-back\">\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"mat-focus-indicator mat-icon-button mat-button-base\">\r\n");
      out.write("									<span class=\"mat-button-wrapper\"><svg\r\n");
      out.write("											viewBox=\"0 0 24 24\" width=\"24px\" height=\"24px\"\r\n");
      out.write("											fill=\"currentColor\" focusable=\"false\"\r\n");
      out.write("											class=\"mat-datepicker-toggle-default-icon \">\r\n");
      out.write("											<path\r\n");
      out.write("												d=\"M19 3h-1V1h-2v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V8h14v11zM7 10h5v5H7z\"></path></svg>\r\n");
      out.write("										<!----></span><span matripple=\"\"\r\n");
      out.write("										class=\"mat-ripple mat-button-ripple mat-button-ripple-round\"></span><span\r\n");
      out.write("										class=\"mat-button-focus-overlay\"></span>\r\n");
      out.write("\r\n");
      out.write("								</button>\r\n");
      out.write("								</mat-datepicker-toggle>\r\n");
      out.write("\r\n");
      out.write("								<input type=\"text\" disabled placeholder=\"여행 끝\"\r\n");
      out.write("									class=\"trip-end input-day\">\r\n");
      out.write("								<mat-datepicker-toggle class=\"calender-back\">\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"mat-focus-indicator mat-icon-button mat-button-base\">\r\n");
      out.write("									<span class=\"mat-button-wrapper\"><svg\r\n");
      out.write("											viewBox=\"0 0 24 24\" width=\"24px\" height=\"24px\"\r\n");
      out.write("											fill=\"currentColor\" focusable=\"false\"\r\n");
      out.write("											class=\"mat-datepicker-toggle-default-icon \">\r\n");
      out.write("											<path\r\n");
      out.write("												d=\"M19 3h-1V1h-2v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V8h14v11zM7 10h5v5H7z\"></path></svg>\r\n");
      out.write("										<!----></span><span matripple=\"\"\r\n");
      out.write("										class=\"mat-ripple mat-button-ripple mat-button-ripple-round\"></span><span\r\n");
      out.write("										class=\"mat-button-focus-overlay\"></span>\r\n");
      out.write("								</button>\r\n");
      out.write("								</mat-datepicker-toggle>\r\n");
      out.write("							</div>\r\n");
      out.write("							<span class=\"desc trip-date-inval cant-submit\"\r\n");
      out.write("								style=\"display: none;\">시작날짜가 끝날짜보다 클 수 없습니다!</span> <span\r\n");
      out.write("								class=\"desc trip-date-none-inval cant-submit\"\r\n");
      out.write("								style=\"display: block;\">여행일정 입력은 필수입니다!</span>\r\n");
      out.write("							<!---->\r\n");
      out.write("							<div id=\"editorjs\" class=\"inner\">\r\n");
      out.write("								<div class=\"codex-editor codex-editor--empty\">\r\n");
      out.write("									<div class=\"codex-editor__redactor\"\r\n");
      out.write("										style=\"padding-bottom: 300px;\">\r\n");
      out.write("										<div class=\"ce-block\">\r\n");
      out.write("											<div class=\"ce-block__content\">\r\n");
      out.write("												<div class=\"ce-paragraph cdx-block\">\r\n");
      out.write("\r\n");
      out.write("													<textarea id=\"summernote\"></textarea>\r\n");
      out.write("\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"codex-editor-overlay\">\r\n");
      out.write("										<div class=\"codex-editor-overlay__container\">\r\n");
      out.write("											<div class=\"codex-editor-overlay__rectangle\"\r\n");
      out.write("												style=\"display: none;\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"ce-inline-toolbar\">\r\n");
      out.write("										<div class=\"ce-inline-toolbar__toggler-and-button-wrapper\">\r\n");
      out.write("											<div class=\"ce-inline-toolbar__dropdown\">\r\n");
      out.write("												<div class=\"ce-inline-toolbar__dropdown-content\"></div>\r\n");
      out.write("												<div class=\"ce-inline-toolbar__dropdown-arrow\">\r\n");
      out.write("													<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\"\r\n");
      out.write("														height=\"24\" fill=\"none\" viewBox=\"0 0 24 24\">\r\n");
      out.write("													<path stroke=\"currentColor\" stroke-linecap=\"round\"\r\n");
      out.write("															stroke-width=\"2\"\r\n");
      out.write("															d=\"M7 10L11.8586 14.8586C11.9367 14.9367 12.0633 14.9367 12.1414 14.8586L17 10\"></path></svg>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"ce-inline-toolbar__buttons\"></div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"ce-inline-toolbar__actions\"></div>\r\n");
      out.write("										<div class=\"ce-conversion-toolbar\">\r\n");
      out.write("											<div class=\"ce-conversion-toolbar__label\">Convert to</div>\r\n");
      out.write("											<div class=\"ce-conversion-toolbar__tools\">\r\n");
      out.write("												<div class=\"ce-conversion-tool\" data-tool=\"paragraph\">\r\n");
      out.write("													<div class=\"ce-conversion-tool__icon\">\r\n");
      out.write("														<svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("															viewBox=\"0.2 -0.3 9 11.4\" width=\"12\" height=\"14\">\r\n");
      out.write("  <path\r\n");
      out.write("																d=\"M0 2.77V.92A1 1 0 01.2.28C.35.1.56 0 .83 0h7.66c.28.01.48.1.63.28.14.17.21.38.21.64v1.85c0 .26-.08.48-.23.66-.15.17-.37.26-.66.26-.28 0-.5-.09-.64-.26a1 1 0 01-.21-.66V1.69H5.6v7.58h.5c.25 0 .45.08.6.23.17.16.25.35.25.6s-.08.45-.24.6a.87.87 0 01-.62.22H3.21a.87.87 0 01-.61-.22.78.78 0 01-.24-.6c0-.25.08-.44.24-.6a.85.85 0 01.61-.23h.5V1.7H1.73v1.08c0 .26-.08.48-.23.66-.15.17-.37.26-.66.26-.28 0-.5-.09-.64-.26A1 1 0 010 2.77z\"></path>\r\n");
      out.write("</svg>\r\n");
      out.write("													</div>\r\n");
      out.write("													텍스트\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"ce-conversion-tool\">\r\n");
      out.write("													<div class=\"ce-conversion-tool__icon\">\r\n");
      out.write("														<svg width=\"10\" height=\"14\"\r\n");
      out.write("															xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 10 14\">\r\n");
      out.write("          <path\r\n");
      out.write("																d=\"M7.6 8.15H2.25v4.525a1.125 1.125 0 0 1-2.25 0V1.125a1.125 1.125 0 1 1 2.25 0V5.9H7.6V1.125a1.125 1.125 0 0 1 2.25 0v11.55a1.125 1.125 0 0 1-2.25 0V8.15z\"></path>\r\n");
      out.write("        </svg>\r\n");
      out.write("													</div>\r\n");
      out.write("													헤더\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"ce-conversion-tool\">\r\n");
      out.write("													<div class=\"ce-conversion-tool__icon\">\r\n");
      out.write("														<svg width=\"17\" height=\"13\" viewBox=\"0 0 17 13\"\r\n");
      out.write("															xmlns=\"http://www.w3.org/2000/svg\"> <path\r\n");
      out.write("																d=\"M5.625 4.85h9.25a1.125 1.125 0 0 1 0 2.25h-9.25a1.125 1.125 0 0 1 0-2.25zm0-4.85h9.25a1.125 1.125 0 0 1 0 2.25h-9.25a1.125 1.125 0 0 1 0-2.25zm0 9.85h9.25a1.125 1.125 0 0 1 0 2.25h-9.25a1.125 1.125 0 0 1 0-2.25zm-4.5-5a1.125 1.125 0 1 1 0 2.25 1.125 1.125 0 0 1 0-2.25zm0-4.85a1.125 1.125 0 1 1 0 2.25 1.125 1.125 0 0 1 0-2.25zm0 9.85a1.125 1.125 0 1 1 0 2.25 1.125 1.125 0 0 1 0-2.25z\"></path></svg>\r\n");
      out.write("													</div>\r\n");
      out.write("													리스트\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"inner\">\r\n");
      out.write("								<div class=\"sch_form tag_box\">\r\n");
      out.write("									<span class=\"prefix\">#</span><input maxlength=\"20\"\r\n");
      out.write("										placeholder=\"태그를 입력해주세요.(최대10개)\" type=\"text\" enterkeyhint=\"go\"\r\n");
      out.write("										class=\"mat-chip-input mat-input-element txtbox\"\r\n");
      out.write("										style=\"width: 100%; margin: 0;\" id=\"mat-chip-list-input-6\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									<mat-chip-list class=\"mat-chip-list\" id=\"mat-chip-list-6\"\r\n");
      out.write("										tabindex=\"-1\" aria-disabled=\"false\" aria-invalid=\"false\"\r\n");
      out.write("										aria-multiselectable=\"false\" aria-orientation=\"horizontal\">\r\n");
      out.write("									<div class=\"mat-chip-list-wrapper hashtag-list-wrapper\">\r\n");
      out.write("										<!---->\r\n");
      out.write("									</div>\r\n");
      out.write("									</mat-chip-list>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"inner\">\r\n");
      out.write("								<div class=\"sch_form\">\r\n");
      out.write("\r\n");
      out.write("									<input placeholder=\"여행기에 주요도시를 입력해 주세요(최소1개,최대10개)\" type=\"text\"\r\n");
      out.write("										class=\"mat-chip-input mat-input-element mat-autocomplete-trigger txtbox search-loaction\"\r\n");
      out.write("										style=\"width: 100%;\" id=\"mat-chip-list-input-7\"\r\n");
      out.write("										autocomplete=\"off\" role=\"combobox\" aria-autocomplete=\"list\"\r\n");
      out.write("										aria-expanded=\"false\" aria-haspopup=\"listbox\">\r\n");
      out.write("									<!---->\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									<mat-chip-list class=\"mat-chip-list\"\r\n");
      out.write("										data-mat-chip-input=\"mat-chip-list-input-6\"\r\n");
      out.write("										id=\"mat-chip-list-6\" tabindex=\"-1\" aria-disabled=\"false\"\r\n");
      out.write("										aria-invalid=\"false\" aria-multiselectable=\"false\"\r\n");
      out.write("										aria-orientation=\"horizontal\">\r\n");
      out.write("									<div class=\"mat-chip-list-wrapper search-loaction-list-wrapper\">\r\n");
      out.write("										<!---->\r\n");
      out.write("									</div>\r\n");
      out.write("									</mat-chip-list>\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"desc\">※ 관련 도시 ( 여행기에 등록된 장소의 도시정보를 분석하여 도시를 자동으로\r\n");
      out.write("									등록하며, 수동으로 직접 등록도 가능합니다. )</p>\r\n");
      out.write("								<p class=\"pdt10\">\r\n");
      out.write("\r\n");
      out.write("									<mat-autocomplete class=\"mat-autocomplete\"><!----></mat-autocomplete>\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"list_btn ta_right\">\r\n");
      out.write("						<!---->\r\n");
      out.write("						<a class=\"btn_st0 active submit-btn\">발행[공개]</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</app-write-travel-note> </app-root>\r\n");
      out.write("	<div class=\"cdk-overlay-container\">\r\n");
      out.write("		<div class=\"cdk-global-overlay-wrapper\" dir=\"ltr\"\r\n");
      out.write("			style=\"justify-content: center; align-items: flex-end;\">\r\n");
      out.write("			<div id=\"cdk-overlay-27\" class=\"cdk-overlay-pane\">\r\n");
      out.write("				<snack-bar-container\r\n");
      out.write("					class=\"mat-snack-bar-container ng-tns-c51-28 ng-trigger ng-trigger-state mat-snack-bar-center \"\r\n");
      out.write("					style=\"transform: scale(1); opacity: 1;\">\r\n");
      out.write("				<div class=\"ng-tns-c51-28\" aria-live=\"assertive\">\r\n");
      out.write("					<div class=\"ng-tns-c51-28\">\r\n");
      out.write("						<simple-snack-bar class=\"mat-simple-snackbar \">\r\n");
      out.write("						<span class=\"mat-simple-snack-bar-content\">최대 10개까지 저장\r\n");
      out.write("							가능합니다.</span><!----></simple-snack-bar>\r\n");
      out.write("						<!---->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				</snack-bar-container>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"cdk-overlay-27\"\r\n");
      out.write("				class=\"cdk-overlay-pane title-schedule-modal\">\r\n");
      out.write("				<snack-bar-container\r\n");
      out.write("					class=\"mat-snack-bar-container ng-tns-c51-28 ng-trigger ng-trigger-state mat-snack-bar-center \"\r\n");
      out.write("					style=\"transform: scale(1); opacity: 1;\">\r\n");
      out.write("				<div class=\"ng-tns-c51-28\" aria-live=\"assertive\">\r\n");
      out.write("					<div class=\"ng-tns-c51-28\">\r\n");
      out.write("						<simple-snack-bar class=\"mat-simple-snackbar \">\r\n");
      out.write("						<span class=\"mat-simple-snack-bar-content\">제목과 일정을 확인해주세요!\r\n");
      out.write("						</span><!----></simple-snack-bar>\r\n");
      out.write("						<!---->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				</snack-bar-container>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"cdk-overlay-27\" class=\"cdk-overlay-pane location-min-modal\">\r\n");
      out.write("				<snack-bar-container\r\n");
      out.write("					class=\"mat-snack-bar-container ng-tns-c51-28 ng-trigger ng-trigger-state mat-snack-bar-center \"\r\n");
      out.write("					style=\"transform: scale(1); opacity: 1;\">\r\n");
      out.write("				<div class=\"ng-tns-c51-28\" aria-live=\"assertive\">\r\n");
      out.write("					<div class=\"ng-tns-c51-28\">\r\n");
      out.write("						<simple-snack-bar class=\"mat-simple-snackbar \">\r\n");
      out.write("						<span class=\"mat-simple-snack-bar-content\">여행도시는 반드시 1개이상은\r\n");
      out.write("							선택해주세요 </span><!----></simple-snack-bar>\r\n");
      out.write("						<!---->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				</snack-bar-container>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/board-form/trip-board-form.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
