/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-26 23:23:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_002droot_002dboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원관리</title>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/admin/admin-board.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/admin/admin-header-nav.css\">\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("		<div class=\"header\">\r\n");
      out.write("			<div class=\"logoImage\">\r\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin.main\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/logo.png\" alt=\"travelers\" style=\"width:158px;\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"title\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<span class=\"ChangeTitle\">추천루트 게시글</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<span><small>관리자모드</small></span>\r\n");
      out.write("			</div>z\r\n");
      out.write("		 </div>\r\n");
      out.write("		 \r\n");
      out.write("		 \r\n");
      out.write("		 <!--mainSidebar -->\r\n");
      out.write("		 	<section class=\"mainContainer\">\r\n");
      out.write("				 ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/admin/mainSidebar.jsp", out, false);
      out.write("\r\n");
      out.write("			<!-- 여기까지 복사 -->\r\n");
      out.write("			\r\n");
      out.write("			<!--mainScreen 회원관리-->\r\n");
      out.write("				<div class=\"mainContent\">\r\n");
      out.write("					<div class=\"memberSearch\">\r\n");
      out.write("						<div class=\"memberSearchInput\">\r\n");
      out.write("							<select>\r\n");
      out.write("								<option value=\"nickName\">작성자</option>\r\n");
      out.write("								<option value=\"box title\">제목</option>\r\n");
      out.write("								<option value=\"box write\">내용</option>\r\n");
      out.write("							</select>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"text\" placeholder=\"검색어를 입력하세요\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/image/search.png\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"memberLists\">\r\n");
      out.write("						<div id=\"root\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<span>총 <div id=\"checkResult\" style=\"width: 10px; height: 10px;\">0</div> 건 </span>\r\n");
      out.write("								<button>삭제</button>\r\n");
      out.write("				       		</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					<table>\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr class=\"tableTh\" style=\"border-top:3px solid #6e6e6e;\">\r\n");
      out.write("									<td class = \"inputCheckBoxAllBtn\"><input class=\"inputCheckBoxAll\"type=\"checkbox\"></td>\r\n");
      out.write("									<td>게시글 번호</td>\r\n");
      out.write("									<td>제목</td>\r\n");
      out.write("									<td>작성자</td>\r\n");
      out.write("									<td>등록날짜</td>\r\n");
      out.write("									<td>조회수</td>\r\n");
      out.write("									<td>하트수</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class = \"inputCheckBoxBtn\"><input class=\"inputCheckBox\" type=\"checkbox\"></td>\r\n");
      out.write("									<td>432</td>\r\n");
      out.write("									<td>안녕</td>\r\n");
      out.write("									<td>USER</td>\r\n");
      out.write("									<td>010-0000-0000</td>\r\n");
      out.write("									<td>민혁</td>\r\n");
      out.write("									<td>1990-02-19</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class = \"inputCheckBoxBtn\"><input class=\"inputCheckBox\" type=\"checkbox\"></td>\r\n");
      out.write("									<td>432</td>\r\n");
      out.write("									<td>안녕</td>\r\n");
      out.write("									<td>USER</td>\r\n");
      out.write("									<td>010-0000-0000</td>\r\n");
      out.write("									<td>민혁</td>\r\n");
      out.write("									<td>1990-02-19</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class = \"inputCheckBoxBtn\"><input class=\"inputCheckBox\" type=\"checkbox\"></td>\r\n");
      out.write("									<td>432</td>\r\n");
      out.write("									<td>안녕</td>\r\n");
      out.write("									<td>USER</td>\r\n");
      out.write("									<td>010-0000-0000</td>\r\n");
      out.write("									<td>민혁</td>\r\n");
      out.write("									<td>1990-02-19</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class = \"inputCheckBoxBtn\"><input class=\"inputCheckBox\" type=\"checkbox\"></td>\r\n");
      out.write("									<td>432</td>\r\n");
      out.write("									<td>안녕</td>\r\n");
      out.write("									<td>USER</td>\r\n");
      out.write("									<td>010-0000-0000</td>\r\n");
      out.write("									<td>민혁</td>\r\n");
      out.write("									<td>1990-02-19</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class = \"inputCheckBoxBtn\"><input class=\"inputCheckBox\" type=\"checkbox\"></td>\r\n");
      out.write("									<td>432</td>\r\n");
      out.write("									<td>안녕</td>\r\n");
      out.write("									<td>USER</td>\r\n");
      out.write("									<td>010-0000-0000</td>\r\n");
      out.write("									<td>민혁</td>\r\n");
      out.write("									<td>1990-02-19</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class = \"inputCheckBoxBtn\"><input class=\"inputCheckBox\" type=\"checkbox\"></td>\r\n");
      out.write("									<td>432</td>\r\n");
      out.write("									<td>안녕</td>\r\n");
      out.write("									<td>USER</td>\r\n");
      out.write("									<td>010-0000-0000</td>\r\n");
      out.write("									<td>민혁</td>\r\n");
      out.write("									<td>1990-02-19</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class = \"inputCheckBoxBtn\"><input class=\"inputCheckBox\" type=\"checkbox\"></td>\r\n");
      out.write("									<td>432</td>\r\n");
      out.write("									<td>안녕</td>\r\n");
      out.write("									<td>USER</td>\r\n");
      out.write("									<td>010-0000-0000</td>\r\n");
      out.write("									<td>민혁</td>\r\n");
      out.write("									<td>1990-02-19</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class = \"inputCheckBoxBtn\"><input class=\"inputCheckBox\" type=\"checkbox\"></td>\r\n");
      out.write("									<td>432</td>\r\n");
      out.write("									<td>안녕</td>\r\n");
      out.write("									<td>USER</td>\r\n");
      out.write("									<td>010-0000-0000</td>\r\n");
      out.write("									<td>민혁</td>\r\n");
      out.write("									<td>1990-02-19</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class = \"inputCheckBoxBtn\"><input class=\"inputCheckBox\" type=\"checkbox\"></td>\r\n");
      out.write("									<td>432</td>\r\n");
      out.write("									<td>안녕</td>\r\n");
      out.write("									<td>USER</td>\r\n");
      out.write("									<td>010-0000-0000</td>\r\n");
      out.write("									<td>민혁</td>\r\n");
      out.write("									<td>1990-02-19</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class = \"inputCheckBoxBtn\"><input class=\"inputCheckBox\" type=\"checkbox\"></td>\r\n");
      out.write("									<td>432</td>\r\n");
      out.write("									<td>안녕</td>\r\n");
      out.write("									<td>USER</td>\r\n");
      out.write("									<td>010-0000-0000</td>\r\n");
      out.write("									<td>민혁</td>\r\n");
      out.write("									<td>1990-02-19</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("\r\n");
      out.write("						<!-- [S] 페이지 컨트롤러 -->\r\n");
      out.write("						<div class=\"page-controller-wrap\">\r\n");
      out.write("\r\n");
      out.write("							<!-- 이전 페이지로 이동하기 -->\r\n");
      out.write("							<a class=\"page-list page-list-move page-before\"> <img\r\n");
      out.write("							   src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAQAAABqrk9lAAAAGElEQVR42mNgAIPi/8X/4QwwE5PBQJADAAKSG3cyVhtXAAAAAElFTkSuQmCC\"\r\n");
      out.write("							   alt=\"이전 페이지로 이동하기 아이콘\"></a> \r\n");
      out.write("							   <a class=\"page-list page-list-first list-on\">1</a> \r\n");
      out.write("							   <a class=\"page-list page-list-second\">2</a> \r\n");
      out.write("							   <a class=\"page-list page-list-third\">3</a> \r\n");
      out.write("							   <a class=\"page-list page-list-fourth\">4</a>\r\n");
      out.write("							   <a class=\"page-list page-list-fifth\">5</a>\r\n");
      out.write("		  \r\n");
      out.write("							<!-- 다음 페이지로 이동하기 -->\r\n");
      out.write("							<a class=\"page-list page-list-move page-after\"> <img\r\n");
      out.write("							   src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAHCAQAAABqrk9lAAAAGUlEQVR42mMo/l/8nwECQEwCHEwGhAlRBgA2mht3SwgzrwAAAABJRU5ErkJggg==\"\r\n");
      out.write("							   alt=\"다음 페이지로 이동하기 아이콘\">\r\n");
      out.write("							</a>\r\n");
      out.write("		  \r\n");
      out.write("						 </div>\r\n");
      out.write("						 <!-- [E] 페이지 컨트롤러 -->\r\n");
      out.write("					</div> \r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/admin/admin-table.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
