/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-09 08:16:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.header_002dfooter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/header-footer/footer.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		<app-footer _ngcontent-akd-c67 _nghost-akd-c65\r\n");
      out.write("			class=\"ng-star-inserted\"> <footer _ngcontent-xjb-c66\r\n");
      out.write("			id=\"footer\">\r\n");
      out.write("			<div _ngcontent-xjb-c66 class=\"in_wrap\">\r\n");
      out.write("				<span _ngcontent-xjb-c66 class=\"btn_top_scroll\"> </span>\r\n");
      out.write("				<nav _ngcontent-xjb-c66 class=\"list_link\">\r\n");
      out.write("					<dl _ngcontent-xjb-c66>\r\n");
      out.write("						<dt _ngcontent-xjb-c66>회사소개</dt>\r\n");
      out.write("						<dd _ngcontent-xjb-c66>\r\n");
      out.write("							<a _ngcontent-xjb-c66>회사소개</a> <a _ngcontent-xjb-c66>브랜드 미디어</a>\r\n");
      out.write("\r\n");
      out.write("							<a _ngcontent-xjb-c66>채용공고</a> <a _ngcontent-xjb-c66\r\n");
      out.write("								href=\"mailto:support@wishbeen.com\"> 제휴문의 </a>\r\n");
      out.write("						</dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("					<dl _ngcontent-xjb-c66>\r\n");
      out.write("						<dt _ngcontent-xjb-c66>고객지원</dt>\r\n");
      out.write("						<dd _ngcontent-xjb-c66>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<a>공지사항</a> <a _ngcontent-xjb-c66>자주묻는질문</a> \r\n");
      out.write("							<a href=\"/questionListOk.questionBoard\">문의하기</a> <a _ngcontent-xjb-c66>위시빈 가이드</a>\r\n");
      out.write("\r\n");
      out.write("						</dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("					<dl _ngcontent-xjb-c66>\r\n");
      out.write("						<dt _ngcontent-xjb-c66>이용약관</dt>\r\n");
      out.write("						<dd _ngcontent-xjb-c66>\r\n");
      out.write("							<a _ngcontent-xjb-c66>이용약관</a> <a _ngcontent-xjb-c66>개인정보\r\n");
      out.write("								처리방침</a> <a _ngcontent-xjb-c66>제3자 정보제공</a>\r\n");
      out.write("						</dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("				</nav>\r\n");
      out.write("				<div _ngcontent-xjb-c66 class=\"info\">\r\n");
      out.write("					<div _ngcontent-xjb-c66 class=\"inner\">\r\n");
      out.write("						<span _ngcontent-xjb-c66> 상호명 : (주)위시빈 </span> <span\r\n");
      out.write("							_ngcontent-xjb-c66> 대표 : 정진원·최명선 </span> <span _ngcontent-xjb-c66\r\n");
      out.write("							class=\"br\"> 개인정보책임자 : 정병근 </span> <span _ngcontent-xjb-c66>\r\n");
      out.write("							사업자등록번호 : 599-88-01021 </span> <span _ngcontent-xjb-c66>\r\n");
      out.write("							통신판매업신고번호 : 제2021-서울중구-2344호 </span> <span _ngcontent-xjb-c66 class=\"br\">\r\n");
      out.write("							<a _ngcontent-xjb-c66\r\n");
      out.write("							href=\"https://www.ftc.go.kr/www/bizCommList.do?key=3765\"\r\n");
      out.write("							target=\"_blank\"> 사업자정보확인 </a>\r\n");
      out.write("						</span> <span _ngcontent-xjb-c66> 광고 및 제휴 : <a _ngcontent-xjb-c66\r\n");
      out.write("							href=\"mailto:support@wishbeen.com\">support@wishbeen.com</a>\r\n");
      out.write("						</span> <span _ngcontent-xjb-c66 class=\"br\"> <a _ngcontent-xjb-c66\r\n");
      out.write("							href=\"mailto:cs@wishbeen.com\">고객센터 : cs@wishbeen.com</a>\r\n");
      out.write("						</span> <span _ngcontent-xjb-c66 class=\"br noti\"> 위시빈은 통신판매중개자이며\r\n");
      out.write("							통신판매의 당사자가 아닙니다. 따라서 위시빈은 상품·거래정보에 대하여 책임을 지지 않습니다. </span> <span\r\n");
      out.write("							_ngcontent-xjb-c66 class=\"br\"> 위시빈 서비스의 모든 콘텐츠는 저작자에게 저작권이\r\n");
      out.write("							있으므로 무단 업로드 혹은 사용 시 법적 책임이 발생할 수 있습니다. </span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div _ngcontent-xjb-c66 class=\"mark_area\">\r\n");
      out.write("						<span _ngcontent-xjb-c66> <img _ngcontent-xjb-c66\r\n");
      out.write("							src=\"https://www.wishbeen.co.kr/assets/images/mark_01.png\"\r\n");
      out.write("							alt=\"iso 9001\"> <em _ngcontent-xjb-c66>KS Q ISO 9001</em>\r\n");
      out.write("						</span> <span _ngcontent-xjb-c66> <img _ngcontent-xjb-c66\r\n");
      out.write("							src=\"https://www.wishbeen.co.kr/assets/images/mark_02.png\"\r\n");
      out.write("							alt=\"iso 14001\"> <em _ngcontent-xjb-c66>KS I ISO 14001</em>\r\n");
      out.write("						</span> <span _ngcontent-xjb-c66> <img _ngcontent-xjb-c66\r\n");
      out.write("							src=\"https://www.wishbeen.co.kr/assets/images/mark_03.png\"\r\n");
      out.write("							alt=\"venture enterprise\"> <em _ngcontent-xjb-c66>Venture\r\n");
      out.write("								Enterprise</em>\r\n");
      out.write("						</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div _ngcontent-xjb-c66>\r\n");
      out.write("						<span _ngcontent-xjb-c66 class=\"copy\">2022 ⓒ Better Than\r\n");
      out.write("							WishBeen.</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</footer> </app-footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
