/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-03 08:48:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.app.domain.VO.user.UserVO;

public final class member_002dinformation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/web_1900_HES/traverse/workspace/project-travelers/WebContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1682164404140L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.app.domain.VO.user.UserVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 UserVO userVO = (UserVO)request.getAttribute("userVO"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Member information</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/mypage/member-information.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/font/font.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("input.memberInfo {\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-bottom: 0.1rem solid #e7e7e7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.btn_st0 {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 10px;\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	line-height: 1.5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=submit] {\r\n");
      out.write("	border: none;\r\n");
      out.write("	background-color: transparent;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<app-root ng-version=\"13.3.12\">\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/mypage/mypage-modal.jsp", out, false);
      out.write("\r\n");
      out.write("		<app-account-management\r\n");
      out.write("			class=\"ng-star-inserted\">\r\n");
      out.write("			<div id=\"content\">\r\n");
      out.write("				<header class=\"sub_header st1\">\r\n");
      out.write("					<div class=\"in_wrap\">\r\n");
      out.write("						<h2>\r\n");
      out.write("							<p class=\"dth2\">계정 관리</p>\r\n");
      out.write("						</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</header>\r\n");
      out.write("		<div class=\"in_wrap\">\r\n");
      out.write("			<nav value=\"false\" class=\"position_r\">\r\n");
      out.write("				<button type=\"button\" class=\"tab_nav_btn mo\">\r\n");
      out.write("					<span>회원 정보</span> \r\n");
      out.write("					<i class=\"ico\"> \r\n");
      out.write("						<img data-brackets-id=\"27106\" src=\"https://www.wishbeen.co.kr/assets/images/svg/chevron_down.svg\" alt=\"더보기\">\r\n");
      out.write("					</i>\r\n");
      out.write("				</button>\r\n");
      out.write("				<ul class=\"tab_nav st01\">\r\n");
      out.write("					<li><a routerlink=\"info\" routerlinkactive=\"active\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/memberInfo.mypage\" class=\"active\"> 회원 정보 </a></li>\r\n");
      out.write("					<li><a routerlink=\"pw-modify\" routerlinkactive=\"active\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/newPassword.mypage\"> 비밀번호 수정 </a></li>\r\n");
      out.write("					<li><a routerlink=\"withdrawal\" routerlinkactive=\"active\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/disaccount.mypage\"> 회원탈퇴 </a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<app-my-info class=\"ng-star-inserted\">\r\n");
      out.write("			<section class=\"my_wrap\">\r\n");
      out.write("				<dl class=\"inner\">\r\n");
      out.write("					<form action=\"\" method=\"post\"\r\n");
      out.write("						id=\"update-info\">\r\n");
      out.write("						<dt class=\"tit\">로그인 정보</dt>\r\n");
      out.write("						<dd>\r\n");
      out.write("							<ul class=\"box_wrap\">\r\n");
      out.write("								<li>\r\n");
      out.write("									<div class=\"th\">이름</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<input type=\"text\" class=\"memberInfo\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<div class=\"th\">닉네임</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<input type=\"text\" class=\"memberInfo\" name=\"nickname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<div class=\"th\">한줄 소개</div>\r\n");
      out.write("									<div class=\"txt\">\r\n");
      out.write("										<input type=\"text\" class=\"memberInfo\" name=\"introducingMessage\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${introducingMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</dd>\r\n");
      out.write("						<dt class=\"tit\">개인 정보</dt>\r\n");
      out.write("						<dd>\r\n");
      out.write("							<ul class=\"box_wrap\">\r\n");
      out.write("								<li>\r\n");
      out.write("									<div class=\"th\">연락처</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<input type=\"text\" class=\"memberInfo\" name=\"phoneNumber\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${phoneNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li>\r\n");
      out.write("									<div class=\"th\">이메일</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<input type=\"text\" class=\"memberInfo\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</dd>\r\n");
      out.write("\r\n");
      out.write("						<dt class=\"tit\">개인정보 유효기간 설정</dt>\r\n");
      out.write("						<dd>\r\n");
      out.write("							<ul class=\"box_wrap\">\r\n");
      out.write("								<li><div class=\"th\">서비스 이용기간 선택</div>\r\n");
      out.write("									<div>\r\n");
      out.write("										<input id=\"agree\" type=\"checkbox\" class=\"chbox\"><label\r\n");
      out.write("											for=\"agree\"> 개인정보를 파기 또는 분리 저장ㆍ관리하여야 하는 서비스 미 이용 기간을\r\n");
      out.write("											회원 탈퇴 시까지로 요청합니다. </label><span class=\"desc\"> * 다만, 별도의 요청이 없을\r\n");
      out.write("											경우 서비스 미이용 기간은 1년으로 합니다. </span>\r\n");
      out.write("									</div></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</dd>\r\n");
      out.write("						<span class=\"btn_area\"><a class=\"btn_st0\"> <input\r\n");
      out.write("								type=\"submit\" value=\"수정\">\r\n");
      out.write("						</a></span>\r\n");
      out.write("					</form>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</section>\r\n");
      out.write("			</app-my-info>\r\n");
      out.write("		\r\n");
      out.write("			<!---->\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</app-account-management> ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/header-footer/footer.jsp", out, false);
      out.write("</app-root>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script src=\"../../static/js/mypage/updateuserInfo.js\">\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
