/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-03 07:49:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.app.domain.VO.user.UserVO;

public final class member_002dquit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/web_1900_HES/traverse/workspace/project-travelers/WebContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1682164404140L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.app.domain.VO.user.UserVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
 UserVO userVO = (UserVO)request.getAttribute("userVO"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원탈퇴</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/mypage/member-quit.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/font/font.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<app-root  ng-version=\"13.3.12\"> ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/mypage/mypage-modal.jsp", out, false);
      out.write(" <app-account-management _nghost-kyu-c85=\"\" class=\"ng-star-inserted\">\r\n");
      out.write("	<div  id=\"content\">\r\n");
      out.write("		<header  class=\"sub_header st1\">\r\n");
      out.write("			<div  class=\"in_wrap\">\r\n");
      out.write("				<h2 >\r\n");
      out.write("					<p  class=\"dth2\">계정 관리</p>\r\n");
      out.write("				</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("		<div  class=\"in_wrap\">\r\n");
      out.write("			<nav  value=\"false\" class=\"position_r\">\r\n");
      out.write("				<button  type=\"button\" class=\"tab_nav_btn mo\">\r\n");
      out.write("					<span >회원 정보</span><i \r\n");
      out.write("						class=\"ico\"><img \r\n");
      out.write("						data-brackets-id=\"27106\"\r\n");
      out.write("						src=\"https://www.wishbeen.co.kr/assets/images/svg/chevron_down.svg\"\r\n");
      out.write("						alt=\"더보기\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("				<ul class=\"tab_nav st01\">\r\n");
      out.write("					<li><a routerlink=\"info\" routerlinkactive=\"active\"\r\n");
      out.write("						href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/memberInfo.mypage\" > 회원 정보 </a></li>\r\n");
      out.write("					<li><a\r\n");
      out.write("						routerlink=\"pw-modify\" routerlinkactive=\"active\"\r\n");
      out.write("						href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/newPassword.mypage\"> 비밀번호 수정 </a></li>\r\n");
      out.write("					<li><a\r\n");
      out.write("						routerlink=\"withdrawal\" routerlinkactive=\"active\"\r\n");
      out.write("						href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/disaccount.mypage\" class=\"active\"> 회원탈퇴 </a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<router-outlet ></router-outlet>\r\n");
      out.write("			<app-membership-withdrawal \r\n");
      out.write("				class=\"ng-star-inserted\">\r\n");
      out.write("			<form novalidate=\"\" action=\"\"\r\n");
      out.write("				class=\"ng-untouched ng-pristine ng-invalid\">\r\n");
      out.write("				<section class=\"my_wrap\">\r\n");
      out.write("					<div class=\"noti_box\">\r\n");
      out.write("						<span class=\"d_block\"> 회원님이 별도로 지정한\r\n");
      out.write("							프로필 이미지는 탈퇴 후에 삭제되지 않습니다. </span><span \r\n");
      out.write("							class=\"d_block\"> 프로필 이미지 노출을 원치 않는 회원님은 <a\r\n");
      out.write("							href=\"/my/account/info\">회원정보</a> 에서 프로필\r\n");
      out.write("							이미지를 수정한 후 탈퇴를 진행해 주세요.\r\n");
      out.write("						</span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<dl class=\"inner\">\r\n");
      out.write("						<dt class=\"tit\">회원탈퇴 신청 정보</dt>\r\n");
      out.write("						<dd >\r\n");
      out.write("							<ul class=\"box_wrap\">\r\n");
      out.write("								<li ><div \r\n");
      out.write("										class=\"th\">아이디</div>\r\n");
      out.write("									<div><input type=\"text\" class=\"memberInfo\" name=\"identification\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.identification}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div></li>\r\n");
      out.write("								<li ><div \r\n");
      out.write("										class=\"th\">\r\n");
      out.write("										</div>\r\n");
      out.write("									<div > <input type=\"text\" class=\"memberInfo\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div></li>\r\n");
      out.write("								<li ><div \r\n");
      out.write("										class=\"th\">비밀번호</div>\r\n");
      out.write("									<div >\r\n");
      out.write("										<input formcontrolname=\"password\"\r\n");
      out.write("											placeholder=\"비밀번호입력\" type=\"password\"\r\n");
      out.write("											class=\"txtbox ng-untouched ng-pristine ng-invalid\">\r\n");
      out.write("										<!---->\r\n");
      out.write("									</div></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("					<dl class=\"inner\">\r\n");
      out.write("						<dt class=\"tit\">탈퇴 사유</dt>\r\n");
      out.write("						<dd >\r\n");
      out.write("							<ul class=\"box_wrap\">\r\n");
      out.write("								<li class=\"ng-star-inserted\"><div\r\n");
      out.write("										>\r\n");
      out.write("										<input \r\n");
      out.write("											formcontrolname=\"secession_reason_idx\" type=\"radio\"\r\n");
      out.write("											class=\"chradio ng-untouched ng-pristine ng-invalid\"\r\n");
      out.write("											id=\"reason1\"><label \r\n");
      out.write("											for=\"reason1\"> 불편한 프로세스 </label>\r\n");
      out.write("									</div></li>\r\n");
      out.write("								<li class=\"ng-star-inserted\"><div\r\n");
      out.write("										>\r\n");
      out.write("										<input \r\n");
      out.write("											formcontrolname=\"secession_reason_idx\" type=\"radio\"\r\n");
      out.write("											class=\"chradio ng-untouched ng-pristine ng-invalid\"\r\n");
      out.write("											id=\"reason2\"><label \r\n");
      out.write("											for=\"reason2\"> 포인트 적립량 부족 </label>\r\n");
      out.write("									</div></li>\r\n");
      out.write("								<li class=\"ng-star-inserted\"><div\r\n");
      out.write("										>\r\n");
      out.write("										<input \r\n");
      out.write("											formcontrolname=\"secession_reason_idx\" type=\"radio\"\r\n");
      out.write("											class=\"chradio ng-untouched ng-pristine ng-invalid\"\r\n");
      out.write("											id=\"reason3\"><label \r\n");
      out.write("											for=\"reason3\"> 청소년에게 유해한 내용입니다. </label>\r\n");
      out.write("									</div></li>\r\n");
      out.write("								<li class=\"ng-star-inserted\"><div\r\n");
      out.write("										>\r\n");
      out.write("										<input \r\n");
      out.write("											formcontrolname=\"secession_reason_idx\" type=\"radio\"\r\n");
      out.write("											class=\"chradio ng-untouched ng-pristine ng-invalid\"\r\n");
      out.write("											id=\"reason8\"><label \r\n");
      out.write("											for=\"reason8\"> 기타 </label>\r\n");
      out.write("									</div></li>\r\n");
      out.write("								<!---->\r\n");
      out.write("								<!---->\r\n");
      out.write("							</ul>\r\n");
      out.write("						</dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("					<div class=\"list_btn wid02\">\r\n");
      out.write("						<a href=\"javascript:history.back();\"\r\n");
      out.write("							class=\"btn_st0\">취소</a><a \r\n");
      out.write("							class=\"btn_st0 active\">회원 탈퇴</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("			</form>\r\n");
      out.write("			</app-membership-withdrawal>\r\n");
      out.write("			<!---->\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</app-account-management>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/header-footer/footer.jsp", out, false);
      out.write(" </app-root>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
