/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-03 09:39:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class my_002dsouvenir_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>여행품 관리</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/header.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/footer.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/mypage/my-souvenir.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/font/font.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<app-root ng-version=\"13.3.12\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/mypage/mypage-modal.jsp", out, false);
      out.write("\r\n");
      out.write("			\r\n");
      out.write("	<app-travel-note-management class=\"ng-star-inserted\">\r\n");
      out.write("	<div id=\"content\">\r\n");
      out.write("		<header class=\"sub_header st1\">\r\n");
      out.write("			<div class=\"in_wrap\">\r\n");
      out.write("				<h2>\r\n");
      out.write("					<p class=\"dth2\">여행품 관리</p>\r\n");
      out.write("				</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("		<div class=\"in_wrap\">\r\n");
      out.write("			<nav value=\"false\" class=\"position_r\">\r\n");
      out.write("				<button type=\"button\" class=\"tab_nav_btn mo\">\r\n");
      out.write("					<span>나의 여행품</span><i\r\n");
      out.write("						class=\"ico\"><img\r\n");
      out.write("						data-brackets-id=\"27106\"\r\n");
      out.write("						src=\"./assets/images/svg/chevron_down.svg\" alt=\"더보기\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("				<ul class=\"tab_nav st01\">\r\n");
      out.write("					<li><a\r\n");
      out.write("						routerlink=\"my\" routerlinkactive=\"active\"\r\n");
      out.write("						href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mysouvenirlike.mypage\" class=\"active\"> 나의 여행품 </a></li>\r\n");
      out.write("					<li><a\r\n");
      out.write("						routerlink=\"like\" routerlinkactive=\"active\"\r\n");
      out.write("						href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mysouvenirlike.mypage\" > 좋아요한 여행품 </a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<router-outlet></router-outlet>\r\n");
      out.write("			<app-my-travel-note-my class=\"ng-star-inserted\">\r\n");
      out.write("			<section class=\"my_wrap\">\r\n");
      out.write("				<header class=\"header ta_right\">\r\n");
      out.write("					<select name=\"\"\r\n");
      out.write("						class=\"selbox ng-untouched ng-pristine ng-valid\"><option\r\n");
      out.write("							 value=\"\">노출 상태 전체</option>\r\n");
      out.write("						<option value=\"published\">발행[공개]</option>\r\n");
      out.write("						<option value=\"temp\">임시저장[비공개]</option>\r\n");
      out.write("						<option value=\"stop\">중지</option></select>\r\n");
      out.write("				</header>\r\n");
      out.write("				<div class=\"trip_list1 clear_v2\">\r\n");
      out.write("					<div class=\"inner ng-star-inserted\">\r\n");
      out.write("						<a></a>\r\n");
      out.write("						<div class=\"img\">\r\n");
      out.write("							<img alt=\"img\"\r\n");
      out.write("								src=\"https://www.wishbeen.co.kr/assets/images/img_default.jpg\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"txt_wrap\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li class=\"geo txt_hide\"><span\r\n");
      out.write("									 class=\"ico_geo\"></span> 여행 지역</li>\r\n");
      out.write("								<li class=\"tit\">여행품 이름</li>\r\n");
      out.write("								<li class=\"txt_hide\"><span\r\n");
      out.write("									 class=\"tag ng-star-inserted\">\r\n");
      out.write("										#여행품 관련 태그 </span>\r\n");
      out.write("								<!----></li>\r\n");
      out.write("								<li><ul\r\n");
      out.write("										class=\"ico_wrap\">\r\n");
      out.write("										<li><span\r\n");
      out.write("											class=\"ico_spot\"></span> 5</li>\r\n");
      out.write("										<li><span\r\n");
      out.write("											class=\"ico_cmt\"></span> 0</li>\r\n");
      out.write("										<li><span\r\n");
      out.write("											class=\"ico_like\"></span> 0</li>\r\n");
      out.write("										<li><span\r\n");
      out.write("											class=\"ico_share\"></span> 0</li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("							<!---->\r\n");
      out.write("							<!---->\r\n");
      out.write("							<a class=\"btn_set\"><img\r\n");
      out.write("								\r\n");
      out.write("								src=\"https://www.wishbeen.co.kr/assets/images/svg/three_dots_vertical.svg\" alt=\"menu\"\r\n");
      out.write("								class=\"ng-star-inserted\">\r\n");
      out.write("							<!----></a>\r\n");
      out.write("							<!---->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!---->\r\n");
      out.write("				</div>\r\n");
      out.write("				<!---->\r\n");
      out.write("			</section>\r\n");
      out.write("			</app-my-travel-note-my>\r\n");
      out.write("			<!---->\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</app-travel-note-management>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/header-footer/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</app-root>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/mypage/fix-delete.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
