/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-03 10:04:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/search/home.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/font/font.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<app-root _nghost-akd-c67 ng-version=\"13.3.12\">\r\n");
      out.write("	<div _ngcontent-akd-c67 id=\"wrap\">\r\n");
      out.write("		\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/mypage/mypage-modal.jsp", out, false);
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<router-outlet _ngcontent-xjb-c68></router-outlet>\r\n");
      out.write("		<app-city-main _nghost-akd-c123 class=\"ng-star-inserted\">\r\n");
      out.write("		<main _ngcontent-akd-c123 id=\"content\">\r\n");
      out.write("			<section _ngcontent-ktr-c79=\"\" class=\"m_visual\">\r\n");
      out.write("				<div _ngcontent-ktr-c79=\"\" class=\"in_wrap\">\r\n");
      out.write("					<div _ngcontent-ktr-c79=\"\" class=\"txt_wrap\">\r\n");
      out.write("						<p _ngcontent-ktr-c79=\"\" class=\"txt\">\r\n");
      out.write("							<span _ngcontent-ktr-c79=\"\" class=\"d_block st1\">세상의 모든 여행</span><span\r\n");
      out.write("								_ngcontent-ktr-c79=\"\" class=\"d_block st2\"><span\r\n");
      out.write("								_ngcontent-ktr-c79=\"\">Travelers</span></span>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p _ngcontent-ktr-c79=\"\" class=\"sch\">\r\n");
      out.write("							<input _ngcontent-ktr-c79=\"\" type=\"text\"\r\n");
      out.write("								placeholder=\"도시나 키워드를 검색해보세요.\">\r\n");
      out.write("							<button _ngcontent-ktr-c79=\"\" type=\"button\">\r\n");
      out.write("								<img _ngcontent-ktr-c79=\"\"\r\n");
      out.write("									src=\"https://www.wishbeen.co.kr/assets/images/svg/search_w.svg\" alt=\"검색\"><span\r\n");
      out.write("									_ngcontent-ktr-c79=\"\" class=\"pc\">검색</span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("			\r\n");
      out.write("			<div _ngcontent-akd-c123 class=\"in_wrap reposition\">\r\n");
      out.write("				<aside class=\"side_bar\">\r\n");
      out.write("								<span _ngcontent-oma-c66=\"\" class=\"btn_top_scroll\"></span>\r\n");
      out.write("							</aside>\r\n");
      out.write("				<nav class=\"tab_sub_wrap withTopBanner\">\r\n");
      out.write("					<ul class=\"tab_nav\">\r\n");
      out.write("						<li><a routerlink=\"home\" class=\"active\" routerlinkactive=\"active\"\r\n");
      out.write("							href=\"/templates/search/home.jsp\"> 홈 </a></li>\r\n");
      out.write("						<li><a routerlink=\"travelogues\" routerlinkactive=\"active\"\r\n");
      out.write("							href=\"/listOk.tripBoard\" > 여행기 </a></li>\r\n");
      out.write("						<li><a routerlink=\"schedules\" routerlinkactive=\"active\"\r\n");
      out.write("							href=\"#\"> 추천루트 </a></li>\r\n");
      out.write("						<li><a routerlink=\"places\" routerlinkactive=\"active\"\r\n");
      out.write("							href=\"/listOk.itemBoard\"> 기념품 목록 </a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("\r\n");
      out.write("				<router-outlet _ngcontent-akd-c123></router-outlet>\r\n");
      out.write("\r\n");
      out.write("				<app-city-home _nghost-akd-c124 class=\"ng-star-inserted\">\r\n");
      out.write("				<section _ngcontent-akd-c124 class=\"city_wrap\">\r\n");
      out.write("					<header _ngcontent-akd-c124 class=\"header\">\r\n");
      out.write("						<p _ngcontent-akd-c124 class=\"tit\">여행기</p>\r\n");
      out.write("						<p _ngcontent-akd-c124 class=\"desc\">여행을 공유 받고 여행에 대한 설렘을\r\n");
      out.write("							느껴보세요.</p>\r\n");
      out.write("						<a _ngcontent-akd-c124 class=\"btn_go\"> 더보기 <img\r\n");
      out.write("							_ngcontent-akd-c124\r\n");
      out.write("							src=\"https://www.wishbeen.co.kr/assets/images/svg/arrow_right.svg\"\r\n");
      out.write("							alt=\"go\">\r\n");
      out.write("						</a>\r\n");
      out.write("					</header>\r\n");
      out.write("					<div _ngcontent-akd-c124 class=\"sl_list ng-star-inserted\">\r\n");
      out.write("						<div _ngcontent-akd-c124 class=\"trip_list clear_v2\">\r\n");
      out.write("							<div _ngcontent-akd-c124 class=\"inner st1 ng-star-inserted\">\r\n");
      out.write("								<a _ngcontent-akd-c124>\r\n");
      out.write("									<p _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("										<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("											src=\"https://test-resize-image.wishbeen.co.kr/eba4b8263e2757b698dbb006ad3c82a5.jpg?w=300&h=300\">\r\n");
      out.write("									</p>\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"txt_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"date\"><span\r\n");
      out.write("											_ngcontent-akd-c124>TRAVEL</span> 여행기간</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"tit\">여행기 제목</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"nick\">작성자 아이디</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"ico_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_cmt\"></span> 댓글수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_like\"></span> 따봉 수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_spot\"></span> 뷰수</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div _ngcontent-akd-c124 class=\"inner st1 ng-star-inserted\">\r\n");
      out.write("								<a _ngcontent-akd-c124>\r\n");
      out.write("									<p _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("										<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("											src=\"https://test-resize-image.wishbeen.co.kr/e610fa06eaf45e89ba83b22635a0efa7.jpg?w=300&h=300\">\r\n");
      out.write("									</p>\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"txt_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"date\"><span\r\n");
      out.write("											_ngcontent-akd-c124>TRAVEL</span> 여행기간</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"tit\">여행기 제목</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"nick\">작성자 아이디</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"ico_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_cmt\"></span> 댓글수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_like\"></span> 따봉 수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_spot\"></span> 뷰수</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div _ngcontent-akd-c124 class=\"inner st1 ng-star-inserted\">\r\n");
      out.write("								<a _ngcontent-akd-c124>\r\n");
      out.write("									<p _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("										<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("											src=\"https://test-resize-image.wishbeen.co.kr/6060d180780e58c1b4317642bcb0185f.jpg?w=300&h=300\">\r\n");
      out.write("									</p>\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"txt_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"date\"><span\r\n");
      out.write("											_ngcontent-akd-c124>TRAVEL</span> 여행기간</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"tit\">여행기 제목</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"nick\">작성자 아이디</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"ico_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_cmt\"></span> 댓글수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_like\"></span> 따봉 수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_spot\"></span> 뷰수</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("\r\n");
      out.write("				<section _ngcontent-akd-c124 class=\"banner_wrap ng-star-inserted\">\r\n");
      out.write("					<div _ngcontent-akd-c124 class=\"in_wrap\">\r\n");
      out.write("						<div _ngcontent-akd-c124 class=\"img pc\" style=\"cursor: pointer;\">\r\n");
      out.write("							<img _ngcontent-akd-c124\r\n");
      out.write("								src=\"https://test-resize-image.wishbeen.co.kr/3492c78225055badb4d41427678bae9f.png\"\r\n");
      out.write("								alt=\"노랑풍선 - 북유럽\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div _ngcontent-akd-c124 class=\"img mo\" style=\"cursor: pointer;\">\r\n");
      out.write("							<img _ngcontent-akd-c124\r\n");
      out.write("								src=\"https://test-resize-image.wishbeen.co.kr/6b06058….png\"\r\n");
      out.write("								alt=\"노랑풍선 - 북유럽\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("				<section _ngcontent-akd-c124 class=\"city_wrap\">\r\n");
      out.write("					<div _ngcontent-akd-c124 class=\"header\">\r\n");
      out.write("						<h2 _ngcontent-akd-c124 class=\"tit\">추천루트</h2>\r\n");
      out.write("						<p _ngcontent-akd-c124 class=\"desc\">다양한 장소와 리뷰로 만들어진 여행일정을\r\n");
      out.write("							확인해보세요.</p>\r\n");
      out.write("						<a _ngcontent-akd-c124 class=\"btn_go\"> 더보기 <img\r\n");
      out.write("							_ngcontent-akd-c124\r\n");
      out.write("							src=\"https://www.wishbeen.co.kr/assets/images/svg/arrow_right.svg\"\r\n");
      out.write("							alt=\"go\">\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div _ngcontent-akd-c124 class=\"sl_list ng-star-inserted\">\r\n");
      out.write("						<div _ngcontent-akd-c124 class=\"trip_list clear_v2\">\r\n");
      out.write("							<div _ngcontent-akd-c124 class=\"inner st1 ng-star-inserted\">\r\n");
      out.write("								<a _ngcontent-akd-c124 href=\"/schedules/456413\"> <span\r\n");
      out.write("									_ngcontent-cbq-c82 class=\"geo\"> <span\r\n");
      out.write("										_ngcontent-akd-c124 class=\"ico_geo_w\"></span> 놀러간곳\r\n");
      out.write("								</span>\r\n");
      out.write("									<div _ngcontent-akd-c124 class=\"img_wrap\">\r\n");
      out.write("										<p _ngcontent-akd-c124 class=\"schedule\"></p>\r\n");
      out.write("										<p _ngcontent-akd-c124 class=\"img st1\">\r\n");
      out.write("											<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("												src=\"https://maps.googleapis.com/maps/api/staticmap?size=300x300&maptype=roadmap&markers=color:0x0D6FFC%7Clabel:1%7C15.119026,145.72821199999998&markers=color:0x0D6FFC%7Clabel:2%7C15.128197819827236,145.69353754232793&markers=color:0x0D6FFC%7Clabel:3%7C15.205952675189694,145.7174413651228&markers=color:0x0D6FFC%7Clabel:4%7C15.209357,145.72021199999995&markers=color:0x0D6FFC%7Clabel:5%7C15.214294,145.71656200000007&markers=color:0x0D6FFC%7Clabel:6%7C15.210155351111428,145.71719139881134&markers=color:0x0D6FFC%7Clabel:7%7C15.127964786730622,145.6936019153443&path=color:0x0D6FFC%7Cweight:5%7C15.119026,145.72821199999998%7C15.128197819827236,145.69353754232793%7C15.205952675189694,145.7174413651228%7C15.209357,145.72021199999995%7C15.214294,145.71656200000007%7C15.210155351111428,145.71719139881134%7C15.127964786730622,145.6936019153443&key=AIzaSyA-46nCXGZeKVzH8MCMMWWRSjKVGfixSvM\">\r\n");
      out.write("										</p>\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"txt_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"date\"><span\r\n");
      out.write("											_ngcontent-akd-c124>PLAN</span> 여행일정</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"tit\">제목</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"nick\">저자</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"ico_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_attr\"></span> 전체장소개수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_like\"></span>추천 수</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div _ngcontent-akd-c124 class=\"inner st1 ng-star-inserted\">\r\n");
      out.write("								<a _ngcontent-akd-c124 href=\"/schedules/456413\"> <span\r\n");
      out.write("									_ngcontent-cbq-c82 class=\"geo\"> <span\r\n");
      out.write("										_ngcontent-akd-c124 class=\"ico_geo_w\"></span> 놀러간곳\r\n");
      out.write("								</span>\r\n");
      out.write("									<div _ngcontent-akd-c124 class=\"img_wrap\">\r\n");
      out.write("										<p _ngcontent-akd-c124 class=\"schedule\"></p>\r\n");
      out.write("										<p _ngcontent-akd-c124 class=\"img st1\">\r\n");
      out.write("											<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("												src=\"https://maps.googleapis.com/maps/api/staticmap?size=300x300&maptype=roadmap&markers=color:0x0D6FFC%7Clabel:1%7C15.2162,145.71806&markers=color:0x0D6FFC%7Clabel:2%7C15.2107677427135,145.7183648804261&markers=color:0x0D6FFC%7Clabel:3%7C15.2095187,145.7179525&markers=color:0x0D6FFC%7Clabel:4%7C15.21420984664743,145.71976717561483&markers=color:0x0D6FFC%7Clabel:5%7C15.213986,145.7156476&path=color:0x0D6FFC%7Cweight:5%7C15.2162,145.71806%7C15.2107677427135,145.7183648804261%7C15.2095187,145.7179525%7C15.21420984664743,145.71976717561483%7C15.213986,145.7156476&key=AIzaSyA-46nCXGZeKVzH8MCMMWWRSjKVGfixSvM\">\r\n");
      out.write("										</p>\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"txt_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"date\"><span\r\n");
      out.write("											_ngcontent-akd-c124>PLAN</span> 여행일정</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"tit\">제목</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"nick\">저자</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"ico_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_attr\"></span> 전체장소개수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_like\"></span> 추천 수</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div _ngcontent-akd-c124 class=\"inner st1 ng-star-inserted\">\r\n");
      out.write("								<a _ngcontent-akd-c124 href=\"/schedules/456413\"> <span\r\n");
      out.write("									_ngcontent-cbq-c82 class=\"geo\"> <span\r\n");
      out.write("										_ngcontent-akd-c124 class=\"ico_geo_w\"></span> 놀러간곳\r\n");
      out.write("								</span>\r\n");
      out.write("									<div _ngcontent-akd-c124 class=\"img_wrap\">\r\n");
      out.write("										<p _ngcontent-akd-c124 class=\"schedule\"></p>\r\n");
      out.write("										<p _ngcontent-akd-c124 class=\"img st1\">\r\n");
      out.write("											<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("												src=\"https://maps.googleapis.com/maps/api/staticmap?size=300x300&maptype=roadmap&markers=color:0x0D6FFC%7Clabel:1%7C37.451541,127.15982099999997&markers=color:0x0D6FFC%7Clabel:2%7C37.446235,126.45602400000008&markers=color:0x0D6FFC%7Clabel:3%7C37.44834333138907,126.4510317815674&markers=color:0x0D6FFC%7Clabel:4%7C15.119026,145.72821199999998&markers=color:0x0D6FFC%7Clabel:5%7C15.147080841346805,145.70070814723817&markers=color:0x0D6FFC%7Clabel:6%7C15.115824,145.705938&path=color:0x0D6FFC%7Cweight:5%7C37.451541,127.15982099999997%7C37.446235,126.45602400000008%7C37.44834333138907,126.4510317815674%7C15.119026,145.72821199999998%7C15.147080841346805,145.70070814723817%7C15.115824,145.705938&key=AIzaSyA-46nCXGZeKVzH8MCMMWWRSjKVGfixSvM\">\r\n");
      out.write("										</p>\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"txt_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"date\"><span\r\n");
      out.write("											_ngcontent-akd-c124>PLAN</span> 여행일정</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"tit\">제목</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"nick\">저자</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"ico_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_attr\"></span> 전체장소개수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_down\"></span> 다운로드 수</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("				<div _ngcontent-akd-c124 class=\"blank_area\"></div>\r\n");
      out.write("				<section _ngcontent-akd-c124 class=\"city_wrap\">\r\n");
      out.write("					<header _ngcontent-akd-c124 class=\"header\">\r\n");
      out.write("						<p _ngcontent-akd-c124 class=\"tit\">여행품 교환</p>\r\n");
      out.write("						<p _ngcontent-akd-c124 class=\"desc\">여행기념품을 다른 여행기념품과 교환해보세요!\r\n");
      out.write("							행복이두배!</p>\r\n");
      out.write("						<a _ngcontent-akd-c124 class=\"btn_go\"> 더보기 <img\r\n");
      out.write("							_ngcontent-akd-c124\r\n");
      out.write("							src=\"https://www.wishbeen.co.kr/assets/images/svg/arrow_right.svg\"\r\n");
      out.write("							alt=\"go\">\r\n");
      out.write("						</a>\r\n");
      out.write("					</header>\r\n");
      out.write("					<div _ngcontent-akd-c124 class=\"sl_list ng-star-inserted\">\r\n");
      out.write("						<div _ngcontent-akd-c124 class=\"trip_list clear_v2\">\r\n");
      out.write("							<div _ngcontent-akd-c124 class=\"inner st1 ng-star-inserted\">\r\n");
      out.write("								<a _ngcontent-akd-c124>\r\n");
      out.write("									<p _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("										<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("											src=\"https://test-resize-image.wishbeen.co.kr/eba4b82….jpg?w=300&h=300\">\r\n");
      out.write("									</p>\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"txt_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"date\"><span\r\n");
      out.write("											_ngcontent-akd-c124>여행품</span> 여행품 아이템 이름</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"tit\">여행품 제목</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"nick\">작성자 아이디</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"ico_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_cmt\"></span> 댓글수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_like\"></span> 따봉 수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_spot\"></span> 뷰수</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div _ngcontent-akd-c124 class=\"inner st1 ng-star-inserted\">\r\n");
      out.write("								<a _ngcontent-akd-c124>\r\n");
      out.write("									<p _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("										<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("											src=\"https://test-resize-image.wishbeen.co.kr/eba4b82….jpg?w=300&h=300\">\r\n");
      out.write("									</p>\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"txt_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"date\"><span\r\n");
      out.write("											_ngcontent-akd-c124>여행품</span> 여행품 아이템 이름</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"tit\">여행품 제목</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"nick\">작성자 아이디</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"ico_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_cmt\"></span> 댓글수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_like\"></span> 따봉 수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_spot\"></span> 뷰수</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div _ngcontent-akd-c124 class=\"inner st1 ng-star-inserted\">\r\n");
      out.write("								<a _ngcontent-akd-c124>\r\n");
      out.write("									<p _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("										<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("											src=\"https://test-resize-image.wishbeen.co.kr/eba4b82….jpg?w=300&h=300\">\r\n");
      out.write("									</p>\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"txt_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"date\"><span\r\n");
      out.write("											_ngcontent-akd-c124>여행품</span> 여행품 아이템 이름</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"tit\">여행품 제목</li>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"nick\">작성자 아이디</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("\r\n");
      out.write("									<ul _ngcontent-akd-c124 class=\"ico_wrap\">\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_cmt\"></span> 댓글수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_like\"></span> 따봉 수</li>\r\n");
      out.write("										<li _ngcontent-akd-c124><span _ngcontent-akd-c124\r\n");
      out.write("											class=\"ico_spot\"></span> 뷰수</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("\r\n");
      out.write("				<section _ngcontent-akd-c124 class=\"city_wrap\">\r\n");
      out.write("					<header _ngcontent-akd-c124 class=\"header\">\r\n");
      out.write("						<p _ngcontent-akd-c124 class=\"tit\">랜드마크</p>\r\n");
      out.write("						<p _ngcontent-akd-c124 class=\"desc\">도시의 이미지를 대표하는 랜드마크 정보를\r\n");
      out.write("							확인해보세요.</p>\r\n");
      out.write("					</header>\r\n");
      out.write("					<ul _ngcontent-akd-c124 id=\"map_slide\"\r\n");
      out.write("						class=\"ng-star-inserted slick-initialized slick-slider\">\r\n");
      out.write("						<button class=\"slick-prev slick-arrow\" aria-label=\"Previous\"\r\n");
      out.write("							type=\"button\" style=\"display: block;\">\r\n");
      out.write("								<span class=\"btn_arrow btn_prev\"></span>\r\n");
      out.write("							</button>\r\n");
      out.write("						<div class=\"slick-list draggable\">\r\n");
      out.write("							<div class=\"slick-track\"\r\n");
      out.write("								style=\"opacity: 1; width: 1188px\">\r\n");
      out.write("								\r\n");
      out.write("								<div class=\"slick-slide slick-cloned\" data-slick-index=\"-4\"\r\n");
      out.write("									aria-hidden=\"true\" style=\"width: 198px;\" tabindex=\"-1\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"inner ng-star-inserted\"\r\n");
      out.write("											style=\"width: 100%; display: inline-block;\"><a\r\n");
      out.write("											_ngcontent-akd-c124 href=\"/places/36270\" tabindex=\"-1\">\r\n");
      out.write("												<div _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("													<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("														src=\"https://test-resize-image.wishbeen.co.kr/eacec8484d7c574d813396303705a0a1.jpg?w=300&h=300\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div _ngcontent-akd-c124>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"cate\">랜드마크 카테고리</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"tit\">랜드마크 이름</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"txt\">랜드마크 한줄 설명</p>\r\n");
      out.write("												</div>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"slick-slide slick-cloned\" data-slick-index=\"-4\"\r\n");
      out.write("									aria-hidden=\"true\" style=\"width: 198px;\" tabindex=\"-1\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"inner ng-star-inserted\"\r\n");
      out.write("											style=\"width: 100%; display: inline-block;\"><a\r\n");
      out.write("											_ngcontent-akd-c124 href=\"/places/36270\" tabindex=\"-1\">\r\n");
      out.write("												<div _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("													<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("														src=\"https://test-resize-image.wishbeen.co.kr/b62b186af60653298a87eca302c23925.jpg?w=300&h=300\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div _ngcontent-akd-c124>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"cate\">랜드마크 카테고리</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"tit\">랜드마크 이름</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"txt\">랜드마크 한줄 설명</p>\r\n");
      out.write("												</div>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"slick-slide slick-cloned\" data-slick-index=\"-4\"\r\n");
      out.write("									aria-hidden=\"true\" style=\"width: 198px;\" tabindex=\"-1\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"inner ng-star-inserted\"\r\n");
      out.write("											style=\"width: 100%; display: inline-block;\"><a\r\n");
      out.write("											_ngcontent-akd-c124 href=\"/places/36270\" tabindex=\"-1\">\r\n");
      out.write("												<div _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("													<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("														src=\"https://test-resize-image.wishbeen.co.kr/1b86817b65cc5a5b86a2fea082b2da5b.jpg?w=300&h=300\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div _ngcontent-akd-c124>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"cate\">랜드마크 카테고리</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"tit\">랜드마크 이름</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"txt\">랜드마크 한줄 설명</p>\r\n");
      out.write("												</div>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"slick-slide slick-cloned\" data-slick-index=\"-4\"\r\n");
      out.write("									aria-hidden=\"true\" style=\"width: 198px;\" tabindex=\"-1\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"inner ng-star-inserted\"\r\n");
      out.write("											style=\"width: 100%; display: inline-block;\"><a\r\n");
      out.write("											_ngcontent-akd-c124 href=\"/places/36270\" tabindex=\"-1\">\r\n");
      out.write("												<div _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("													<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("														src=\"https://test-resize-image.wishbeen.co.kr/516b7b89a3875d60b843648945c10e65.jpg?w=300&h=300\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div _ngcontent-akd-c124>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"cate\">랜드마크 카테고리</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"tit\">랜드마크 이름</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"txt\">랜드마크 한줄 설명</p>\r\n");
      out.write("												</div>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"slick-slide slick-cloned\" data-slick-index=\"-4\"\r\n");
      out.write("									aria-hidden=\"true\" style=\"width: 198px;\" tabindex=\"-1\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"inner ng-star-inserted\"\r\n");
      out.write("											style=\"width: 100%; display: inline-block;\"><a\r\n");
      out.write("											_ngcontent-akd-c124 href=\"/places/36270\" tabindex=\"-1\">\r\n");
      out.write("												<div _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("													<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("														src=\"https://test-resize-image.wishbeen.co.kr/eacec8484d7c574d813396303705a0a1.jpg?w=300&h=300\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div _ngcontent-akd-c124>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"cate\">랜드마크 카테고리</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"tit\">랜드마크 이름</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"txt\">랜드마크 한줄 설명</p>\r\n");
      out.write("												</div>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"slick-slide slick-cloned\" data-slick-index=\"-4\"\r\n");
      out.write("									aria-hidden=\"true\" style=\"width: 198px;\" tabindex=\"-1\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"inner ng-star-inserted\"\r\n");
      out.write("											style=\"width: 100%; display: inline-block;\"><a\r\n");
      out.write("											_ngcontent-akd-c124 href=\"/places/36270\" tabindex=\"-1\">\r\n");
      out.write("												<div _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("													<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("														src=\"https://test-resize-image.wishbeen.co.kr/b62b186af60653298a87eca302c23925.jpg?w=300&h=300\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div _ngcontent-akd-c124>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"cate\">랜드마크 카테고리</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"tit\">랜드마크 이름</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"txt\">랜드마크 한줄 설명</p>\r\n");
      out.write("												</div>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"slick-slide slick-cloned\" data-slick-index=\"-4\"\r\n");
      out.write("									aria-hidden=\"true\" style=\"width: 198px;\" tabindex=\"-1\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"inner ng-star-inserted\"\r\n");
      out.write("											style=\"width: 100%; display: inline-block;\"><a\r\n");
      out.write("											_ngcontent-akd-c124 href=\"/places/36270\" tabindex=\"-1\">\r\n");
      out.write("												<div _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("													<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("														src=\"https://test-resize-image.wishbeen.co.kr/1b86817b65cc5a5b86a2fea082b2da5b.jpg?w=300&h=300\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div _ngcontent-akd-c124>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"cate\">랜드마크 카테고리</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"tit\">랜드마크 이름</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"txt\">랜드마크 한줄 설명</p>\r\n");
      out.write("												</div>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"slick-slide slick-cloned\" data-slick-index=\"-4\"\r\n");
      out.write("									aria-hidden=\"true\" style=\"width: 198px;\" tabindex=\"-1\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"inner ng-star-inserted\"\r\n");
      out.write("											style=\"width: 100%; display: inline-block;\"><a\r\n");
      out.write("											_ngcontent-akd-c124 href=\"/places/36270\" tabindex=\"-1\">\r\n");
      out.write("												<div _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("													<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("														src=\"https://test-resize-image.wishbeen.co.kr/516b7b89a3875d60b843648945c10e65.jpg?w=300&h=300\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div _ngcontent-akd-c124>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"cate\">랜드마크 카테고리</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"tit\">랜드마크 이름</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"txt\">랜드마크 한줄 설명</p>\r\n");
      out.write("												</div>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"slick-slide slick-cloned\" data-slick-index=\"-4\"\r\n");
      out.write("									aria-hidden=\"true\" style=\"width: 198px;\" tabindex=\"-1\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"inner ng-star-inserted\"\r\n");
      out.write("											style=\"width: 100%; display: inline-block;\"><a\r\n");
      out.write("											_ngcontent-akd-c124 href=\"/places/36270\" tabindex=\"-1\">\r\n");
      out.write("												<div _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("													<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("														src=\"https://test-resize-image.wishbeen.co.kr/eacec8484d7c574d813396303705a0a1.jpg?w=300&h=300\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div _ngcontent-akd-c124>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"cate\">랜드마크 카테고리</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"tit\">랜드마크 이름</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"txt\">랜드마크 한줄 설명</p>\r\n");
      out.write("												</div>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"slick-slide slick-cloned\" data-slick-index=\"-4\"\r\n");
      out.write("									aria-hidden=\"true\" style=\"width: 198px;\" tabindex=\"-1\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"inner ng-star-inserted\"\r\n");
      out.write("											style=\"width: 100%; display: inline-block;\"><a\r\n");
      out.write("											_ngcontent-akd-c124 href=\"/places/36270\" tabindex=\"-1\">\r\n");
      out.write("												<div _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("													<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("														src=\"https://test-resize-image.wishbeen.co.kr/b62b186af60653298a87eca302c23925.jpg?w=300&h=300\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div _ngcontent-akd-c124>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"cate\">랜드마크 카테고리</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"tit\">랜드마크 이름</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"txt\">랜드마크 한줄 설명</p>\r\n");
      out.write("												</div>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"slick-slide slick-cloned\" data-slick-index=\"-4\"\r\n");
      out.write("									aria-hidden=\"true\" style=\"width: 198px;\" tabindex=\"-1\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"inner ng-star-inserted\"\r\n");
      out.write("											style=\"width: 100%; display: inline-block;\"><a\r\n");
      out.write("											_ngcontent-akd-c124 href=\"/places/36270\" tabindex=\"-1\">\r\n");
      out.write("												<div _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("													<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("														src=\"https://test-resize-image.wishbeen.co.kr/1b86817b65cc5a5b86a2fea082b2da5b.jpg?w=300&h=300\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div _ngcontent-akd-c124>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"cate\">랜드마크 카테고리</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"tit\">랜드마크 이름</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"txt\">랜드마크 한줄 설명</p>\r\n");
      out.write("												</div>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"slick-slide slick-cloned\" data-slick-index=\"-4\"\r\n");
      out.write("									aria-hidden=\"true\" style=\"width: 198px;\" tabindex=\"-1\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<li _ngcontent-akd-c124 class=\"inner ng-star-inserted\"\r\n");
      out.write("											style=\"width: 100%; display: inline-block;\"><a\r\n");
      out.write("											_ngcontent-akd-c124 href=\"/places/36270\" tabindex=\"-1\">\r\n");
      out.write("												<div _ngcontent-akd-c124 class=\"img\">\r\n");
      out.write("													<img _ngcontent-akd-c124 alt=\"img\"\r\n");
      out.write("														src=\"https://test-resize-image.wishbeen.co.kr/516b7b89a3875d60b843648945c10e65.jpg?w=300&h=300\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div _ngcontent-akd-c124>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"cate\">랜드마크 카테고리</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"tit\">랜드마크 이름</p>\r\n");
      out.write("													<p _ngcontent-akd-c124 class=\"txt\">랜드마크 한줄 설명</p>\r\n");
      out.write("												</div>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button class=\"slick-next slick-arrow\" aria-label=\"Next\"\r\n");
      out.write("							type=\"button\" style=\"display: block;\">\r\n");
      out.write("							<span class=\"btn_arrow btn_next\"></span>\r\n");
      out.write("							</button>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</section>\r\n");
      out.write("				</app-city-home>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</main>\r\n");
      out.write("		</app-city-main>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/header-footer/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	</app-root>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/search/home.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
