/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-03 09:03:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.costomer_002dcenter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class faq_002detc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"../../static/css/font/font.css\" type=\"text/css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../static/css/costomer-center/faq.css\" type=\"text/css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../static/css/home.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../static/css/header.css\" type=\"text/css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../../static/css/footer.css\" type=\"text/css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<app-root>\r\n");
      out.write("	<div>\r\n");
      out.write("\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/mypage/mypage-modal.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<app-customer-center class=\"ng-star-inserted\">\r\n");
      out.write("		<section id=\"content\" class=\"withTopBanner\" style=\"padding: 11rem 0 0\">\r\n");
      out.write("			<div class=\"sub_header st3\">\r\n");
      out.write("				<div class=\"in_wrap\">\r\n");
      out.write("					<h2 class=\"dth1\" style=\"position: relative\">고객지원</h2>\r\n");
      out.write("					<h3 class=\"dth2\" style=\"padding-top: 0px\">자주묻는질문</h3>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"in_wrap\">\r\n");
      out.write("				<div class=\"tab_sub_wrap withTopBanner\">\r\n");
      out.write("					<ul class=\"tab_nav\">\r\n");
      out.write("						<li><a routerlink=\"notice\" routerlinkactive=\"active\"\r\n");
      out.write("							href=\"/customer-center/notice\">공지사항</a></li>\r\n");
      out.write("						<li><a class=\"active\" routerlink=\"faq\"\r\n");
      out.write("							routerlinkactive=\"active\" href=\"/customer-center/faq\">자주묻는질문</a></li>\r\n");
      out.write("						<li><a routerlink=\"qna\" routerlinkactive=\"active\"\r\n");
      out.write("							href=\"/customer-center/qna\">문의하기</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<router-outlet></router-outlet>\r\n");
      out.write("				<app-customer-center-notice-list class=\"ng-star-inserted\">\r\n");
      out.write("				<section class=\"board_wrap\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"cate_box\">\r\n");
      out.write("						<button routerlink=\"join\" routerlinkactive=\"active\" type=\"button\"\r\n");
      out.write("							tabindex=\"0\">회원가입</button>\r\n");
      out.write("						<button routerlink=\"travelogue\" routerlinkactive=\"active\"\r\n");
      out.write("							type=\"button\" tabindex=\"0\">여행기 작성</button>\r\n");
      out.write("						<button routerlink=\"schedule\" routerlinkactive=\"active\"\r\n");
      out.write("							type=\"button\" tabindex=\"0\">여행일정 작성</button>\r\n");
      out.write("						<button routerlink=\"point_save\" routerlinkactive=\"active\"\r\n");
      out.write("							type=\"button\" tabindex=\"0\">포인트</button>\r\n");
      out.write("						<button routerlink=\"etc\" routerlinkactive=\"active\" type=\"button\"\r\n");
      out.write("							tabindex=\"0\" class=\"active\">기타</button>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<header class=\"board_header\">\r\n");
      out.write("						<div class=\"search_form\">\r\n");
      out.write("							<input placeholder=\"검색어를 입력하세요\" type=\"search\"\r\n");
      out.write("								class=\"txtbox ng-untouched ng-pristine ng-valid\">\r\n");
      out.write("							<button type=\"button\">\r\n");
      out.write("								<img\r\n");
      out.write("									src=\"https://www.wishbeen.co.kr/assets/images/svg/search.svg\"\r\n");
      out.write("									alt=\"검색\">\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!---->\r\n");
      out.write("					</header>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"faq_list\">\r\n");
      out.write("						<dl class=\"inner ng-star-inserted\">\r\n");
      out.write("							<dt>\r\n");
      out.write("								<span>휴면 회원을 해제하고 싶어요.</span><span><img\r\n");
      out.write("									src=\"https://www.wishbeen.co.kr/assets/images/svg/chevron_down.svg\"\r\n");
      out.write("									alt=\"더보기\"></span>\r\n");
      out.write("							</dt>\r\n");
      out.write("							<dd>\r\n");
      out.write("								<p>휴면 해제를 원하시는 회원ID 로 로그인을 시도하시면 인증 과정 완료 후 휴면 해제 가능합니다.</p>\r\n");
      out.write("							</dd>\r\n");
      out.write("						</dl>\r\n");
      out.write("						<dl class=\"inner ng-star-inserted\">\r\n");
      out.write("							<dt>\r\n");
      out.write("								<span>탈퇴 후 재가입 할 수 있나요?</span><span><img\r\n");
      out.write("									src=\"https://www.wishbeen.co.kr/assets/images/svg/chevron_down.svg\"\r\n");
      out.write("									alt=\"더보기\"></span>\r\n");
      out.write("							</dt>\r\n");
      out.write("							<dd>\r\n");
      out.write("								<p>탈퇴 후 30일 이후 재가입이 가능합니다.</p>\r\n");
      out.write("								<p>단, 회원 탈퇴 시에는 적립된 포인트와 콘텐츠기록이 모두 삭제되니 신중하게 결정해 주세요.</p>\r\n");
      out.write("								<p>감사합니다.</p>\r\n");
      out.write("							</dd>\r\n");
      out.write("						</dl>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"list_btn pc\">\r\n");
      out.write("						<!---->\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"pagination pc\">\r\n");
      out.write("						<li><a><img\r\n");
      out.write("								src=\"https://www.wishbeen.co.kr/assets/images/svg/chevron_double_left.svg\"\r\n");
      out.write("								alt=\"처음\"></a></li>\r\n");
      out.write("						<li><a><img\r\n");
      out.write("								src=\"https://www.wishbeen.co.kr/assets/images/svg/chevron_left.svg\"\r\n");
      out.write("								alt=\"이전\"></a></li>\r\n");
      out.write("						<li><a class=\"active ng-star-inserted\"> 1 </a> <!----></li>\r\n");
      out.write("						<li><a><img\r\n");
      out.write("								src=\"https://www.wishbeen.co.kr/assets/images/svg/chevron_right.svg\"\r\n");
      out.write("								alt=\"다음\"></a></li>\r\n");
      out.write("						<li><a><img\r\n");
      out.write("								src=\"https://www.wishbeen.co.kr/assets/images/svg/chevron_double_right.svg\"\r\n");
      out.write("								alt=\"마지막\"></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<!---->\r\n");
      out.write("				</section>\r\n");
      out.write("				</app-customer-center-notice-list>\r\n");
      out.write("				<!---->\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		</app-customer-center>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/header-footer/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	</app-root>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"../../static/js/costomer-center/faq.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
