/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-03 09:15:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.costomer_002dcenter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qna_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/font/font.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/costomer-center/qna.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<app-root>\r\n");
      out.write("	<div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/mypage/mypage-modal.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<app-customer-center  class=\"ng-star-inserted\">\r\n");
      out.write("		<section id=\"content\" class=\"withTopBanner\" style=\"padding: 11rem 0 0\">\r\n");
      out.write("			<div class=\"sub_header st3\">\r\n");
      out.write("				<div class=\"in_wrap\">\r\n");
      out.write("					<h2 class=\"dth1\" style=\"position: relative\">고객지원</h2>\r\n");
      out.write("					<h3 class=\"dth2\" style=\"padding-top: 0px\">문의하기</h3>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"in_wrap\">\r\n");
      out.write("				<div class=\"tab_sub_wrap withTopBanner\">\r\n");
      out.write("					<ul class=\"tab_nav\">\r\n");
      out.write("						<li><a routerlink=\"notice\" routerlinkactive=\"active\"\r\n");
      out.write("							href=\"announcement.noticeBoard\">공지사항</a></li>\r\n");
      out.write("						<li><a routerlink=\"faq\" routerlinkactive=\"active\"\r\n");
      out.write("							href=\"/faq.noticeBoard\">자주묻는질문</a></li>\r\n");
      out.write("						<li><a routerlink=\"qna\" routerlinkactive=\"active\"\r\n");
      out.write("							href=\"questionListOk.questionBoard\" class=\"active\">문의하기</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<router-outlet></router-outlet>\r\n");
      out.write("				<app-customer-center-notice-list\r\n");
      out.write("					class=\"ng-star-inserted\">\r\n");
      out.write("				<section class=\"board_wrap\">\r\n");
      out.write("					<header class=\"board_header\">\r\n");
      out.write("						<div class=\"search_form\">\r\n");
      out.write("							<input placeholder=\"검색어를 입력하세요\"\r\n");
      out.write("								type=\"search\" class=\"txtbox ng-untouched ng-pristine ng-valid\">\r\n");
      out.write("							<button type=\"button\">\r\n");
      out.write("								<img\r\n");
      out.write("									src=\"https://www.wishbeen.co.kr/assets/images/svg/search.svg\"\r\n");
      out.write("									alt=\"검색\">\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!---->\r\n");
      out.write("					</header>\r\n");
      out.write("					<div class=\"board_list\">\r\n");
      out.write("						<div class=\"board_tr th\">\r\n");
      out.write("							<div style=\"width: 15%;\">NO</div>\r\n");
      out.write("							<div>제목</div>\r\n");
      out.write("							<div style=\"width: 20%;\">등록일시</div>\r\n");
      out.write("							<div style=\"width: 10%;\">상태</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("						<div class=\"board_tr noti ng-star-inserted\">\r\n");
      out.write("													\r\n");
      out.write("						</div>\r\n");
      out.write("					\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"list_btn pc\">\r\n");
      out.write("						<div class=\"ta_right\">\r\n");
      out.write("							<a class=\"btn_st1\" href=\"/write.questionBoard\">글쓰기</a>\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<ul class=\"pagination pc\">\r\n");
      out.write("						<li><a><img src=\"https://www.wishbeen.co.kr/assets/images/svg/chevron_double_left.svg\" alt=\"처음\"></a></li>\r\n");
      out.write("						<li><a><img src=\"https://www.wishbeen.co.kr/assets/images/svg/chevron_left.svg\" alt=\"이전\"></a></li>\r\n");
      out.write("						<li><a\r\n");
      out.write("							class=\"active ng-star-inserted\"> 1 </a> <!----></li>\r\n");
      out.write("						<li><a><img src=\"https://www.wishbeen.co.kr/assets/images/svg/chevron_right.svg\" alt=\"다음\"></a></li>\r\n");
      out.write("						<li><a><img src=\"https://www.wishbeen.co.kr/assets/images/svg/chevron_double_right.svg\" alt=\"마지막\"></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<!---->\r\n");
      out.write("				</section>\r\n");
      out.write("				</app-customer-center-notice-list>\r\n");
      out.write("				<!---->\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		</app-customer-center>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/header-footer/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	</app-root>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script> let questionboards = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${questionboards}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;</script>\r\n");
      out.write("<script>console.log(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${questionboards}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);</script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/costomer-center/board.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/costomer-center/list.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
